### ISSUE TITLE
[Meta] Follow-up improvements related to equation formulations

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#1321]
#1275 introduces the ability to solve different approximations of our equations. There are a number of follow-up projects that should be addressed over the next months. This issue serves as a collection to keep track of the changes. Everybody is welcome to address single issues, please mention here that you are working on a specific task to avoid duplicated efforts. If you want to add additional tasks feel free to post them, but please make sure they are directly related, so that this issue does not transform into "things that should be improved in ASPECT in general".

- [ ] Add a cookbook explaining the use of different formulations
- [ ] Add a special material model for simple Boussinesq approximation models (with one input parameter that is called "Rayleigh number")
- [ ] Decide upon the future default approximation for compressibility in ASPECT
- [ ] Decide, which existing cookbooks should be transferred to simpler approximations
- [ ] Now that we have defined a reference state (in the adiabatic conditions), we should finally remove the `reference_...` functions from the material model interface (at least deprecate them), and thus close #64
