### ISSUE TITLE
Future features and improvements for Viscoelastic Plastic material model

### ISSUE THREAD

**Issue by naliboff** [geodynamics/aspect#2413]
- [x] Merge initial pull request (#2412) after review
- [x] Add viscoelastic-plastic shear band benchmark
- [x] Put the functionality of #2412 into the viscoplastic material model
- [x] Make sure that all tests still work 
- [x] Deprecate and eventually remove the viscoelatic material model

**Comment by jdannberg** [comment]
I've looked at this for a bit, and my opinion would be instead to

- [ ] put the functionality of #2412 into the viscoplastic material model
- [ ] make sure that all tests still work
- [ ] deprecate and eventually remove the viscoelatic material model

This way, this is all independent of simplifying/refactoring the material models, and we can do that at any point before or after.

**Comment by naliboff** [comment]
Last relevant item checked off the list with #3439
