### ISSUE TITLE
[Meta] Free surface improvements

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/aspect#3720]
This is a list of issues about improving the mesh deformation implementation:

- [ ] initial topography and mesh deformation: 
  - [ ] #3402
  - [ ] #3403
  - [ ] #3399
- [ ] particles and mesh deformation:
  - [ ] #3016
- [ ] Improving the free surface solver:
  - [ ] #2969 
  - [ ] #3110
 - [ ] Use a better surface advection scheme: 
   - [ ] #3717
 - [ ] Advect free surface inside nonlinear solver: #3718.
- [ ] Using the same finite element for mesh deformation and surface velocity: #3719
- [ ] Create a topography visualization postprocessor #1270

If you are interested in working on any of these issues please comment in the respective issue threads. If I have forgotten an issue please comment in this issue. I will update this meta issue to keep track of what has or has not been tackled.

**Comment by anne-glerum** [comment]
The `topography` post processor has an option to write the surface topography to file for x,y surface coordinates. Would that be sufficient?
